### ISSUE TITLE
gunicorn configuration problem in production

### ISSUE THREAD

**Issue by nitinpaul** [tifrh/sawaliram#21]
While setting up our production server [CentOS 7], gunicorn is throwing error. Sharing the config details and logs from nginx and gunicorn. 

```
$ vi /etc/systemd/system/gunicorn.service

[Unit]
Description=gunicorn daemon
After=network.target

[Service]
User=sawaliram
Group=sawaliram
WorkingDirectory=/home/sawaliram/sawaliram/website/code
ExecStart=/home/sawaliram/sawaliram/website/gunicorn_start

[Install]
WantedBy=multi-user.target
```

Note: /home/sawaliram/sawaliram/website/code is where the manage.py file is located.

```
$ vi /home/sawaliram/sawaliram/website/gunicorn_start

#!/bin/bash

DJANGODIR=/home/sawaliram/sawaliram/website/code
USER=sawaliram
GROUP=sawaliram
BIND=unix:/home/sawaliram/sawaliram/website/run/sawaliram.sock
DJANGO_SETTINGS_MODULE=core.settings
DJANGO_WSGI_MODULE=core.wsgi

cd $DJANGODIR
source ../env/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name "core" \
  --workers 3 \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=error \
  --log-file=- \
```
```
$ vi /etc/nginx/conf.d/sawaliram.conf

upstream app_server {
    server unix:/home/sawaliram/sawaliram/website/run/sawaliram.sock fail_timeout=0;
}

server {
    listen 80;
    server_name 10.10.9.33;

    keepalive_timeout 5;
    client_max_body_size 4G;

    access_log /home/sawaliram/sawaliram/website/logs/nginx-access.log;
    error_log /home/sawaliram/sawaliram/website/logs/nginx-error.log;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias /home/sawaliram/sawaliram/website/code/staticfiles/;
    }

    location /media/ {
        alias /home/sawaliram/sawaliram/website/code/media/;
    }

    location / {
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://app_server;
    }
}
```

systemctl status reports for gunicorn and nginx :
```
$ sudo systemctl status -l gunicorn

gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2019-03-07 12:29:08 IST; 1h 52min ago
 Main PID: 5444 (code=exited, status=1/FAILURE)

Mar 07 12:29:08 sawaliram.tifrh.res.in gunicorn_start[5444]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
Mar 07 12:29:08 sawaliram.tifrh.res.in gunicorn_start[5444]: time.sleep(0.1)
Mar 07 12:29:08 sawaliram.tifrh.res.in gunicorn_start[5444]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
Mar 07 12:29:08 sawaliram.tifrh.res.in gunicorn_start[5444]: self.reap_workers()
Mar 07 12:29:08 sawaliram.tifrh.res.in gunicorn_start[5444]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
Mar 07 12:29:08 sawaliram.tifrh.res.in gunicorn_start[5444]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Mar 07 12:29:08 sawaliram.tifrh.res.in gunicorn_start[5444]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Mar 07 12:29:08 sawaliram.tifrh.res.in systemd[1]: gunicorn.service: main process exited, code=exited, status=1/FAILURE
Mar 07 12:29:08 sawaliram.tifrh.res.in systemd[1]: Unit gunicorn.service entered failed state.
Mar 07 12:29:08 sawaliram.tifrh.res.in systemd[1]: gunicorn.service failed.
```
```
$ vi sudo systemctl status -l nginx

nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-03-06 17:50:28 IST; 20h ago
 Main PID: 1085 (nginx)
   CGroup: /system.slice/nginx.service
           ├─1085 nginx: master process /usr/sbin/ngin
           └─1088 nginx: worker proces

Mar 06 17:50:28 sawaliram.tifrh.res.in systemd[1]: Starting The nginx HTTP and reverse proxy server...
Mar 06 17:50:28 sawaliram.tifrh.res.in nginx[979]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Mar 06 17:50:28 sawaliram.tifrh.res.in nginx[979]: nginx: configuration file /etc/nginx/nginx.conf test is successful
Mar 06 17:50:28 sawaliram.tifrh.res.in systemd[1]: Failed to read PID from file /run/nginx.pid: Invalid argument
Mar 06 17:50:28 sawaliram.tifrh.res.in systemd[1]: Started The nginx HTTP and reverse proxy server.
```

The nginx service seems to be running but the error logs have this:
```
2019/03/06 10:32:44 [crit] 7303#0: *39 connect() to unix:/home/sawaliram/sawaliram/website/run/sawaliram.sock failed (2: No such file or directory) while connecting to upstream, client: 10.8.13.174, server: 10.10.9.33, request: "GET /dashboard/login/?next=/dashboard/ HTTP/1.1", upstream: "http://unix:/home/sawaliram/sawaliram/website/run/sawaliram.sock:/dashboard/login/?next=/dashboard/", host: "10.10.9.33"
2019/03/06 10:32:49 [crit] 7303#0: *39 connect() to unix:/home/sawaliram/sawaliram/website/run/sawaliram.sock failed (2: No such file or directory) while connecting to upstream, client: 10.8.13.174, server: 10.10.9.33, request: "GET /dashboard HTTP/1.1", upstream: "http://unix:/home/sawaliram/sawaliram/website/run/sawaliram.sock:/dashboard", host: "10.10.9.33"
2019/03/07 10:58:47 [crit] 1088#0: *7 connect() to unix:/home/sawaliram/sawaliram/website/run/sawaliram.sock failed (2: No such file or directory) while connecting to upstream, client: 10.8.13.207, server: 10.10.9.33, request: "GET / HTTP/1.1", upstream: "http://unix:/home/sawaliram/sawaliram/website/run/sawaliram.sock:/", host: "10.10.9.33"
``` 
This is probably because the gunicorn doesn't launch correctly and therefore the sock file is never created.

I tried running gunicorn from inside the virtual environment to see what errors are thrown, but it didn't throw any errors. Posting the log:
```
$ gunicorn --log-file=- --log-level debug core.wsgi:application

[2019-03-07 14:47:46 +0530] [6008] [DEBUG] Current configuration:
  config: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/sawaliram/sawaliram/website/code
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix: 
  proc_name: None
  default_proc_name: core.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f9d73a2d730>
  on_reload: <function OnReload.on_reload at 0x7f9d73a2d840>
  when_ready: <function WhenReady.when_ready at 0x7f9d73a2d950>
  pre_fork: <function Prefork.pre_fork at 0x7f9d73a2da60>
  post_fork: <function Postfork.post_fork at 0x7f9d73a2db70>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f9d73a2dc80>
  worker_int: <function WorkerInt.worker_int at 0x7f9d73a2dd90>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f9d73a2dea0>
  pre_exec: <function PreExec.pre_exec at 0x7f9d737a5048>
  pre_request: <function PreRequest.pre_request at 0x7f9d737a5158>
  post_request: <function PostRequest.post_request at 0x7f9d737a51e0>
  child_exit: <function ChildExit.child_exit at 0x7f9d737a52f0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f9d737a5400>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f9d737a5510>
  on_exit: <function OnExit.on_exit at 0x7f9d737a5620>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2019-03-07 14:47:46 +0530] [6008] [INFO] Starting gunicorn 19.9.0
[2019-03-07 14:47:46 +0530] [6008] [DEBUG] Arbiter booted
[2019-03-07 14:47:46 +0530] [6008] [INFO] Listening at: http://127.0.0.1:8000 (6008)
[2019-03-07 14:47:46 +0530] [6008] [INFO] Using worker: sync
[2019-03-07 14:47:46 +0530] [6011] [INFO] Booting worker with pid: 6011
[2019-03-07 14:47:46 +0530] [6008] [DEBUG] 1 workers
```
Posting the directory structures and permissions in case it's a permissions problem:
```
$ cd /home/sawaliram/sawaliram/website && ls -al

drwxrwxr-x. 6 sawaliram sawaliram   69 Mar  7 14:05 .
drwxrwxr-x. 3 sawaliram nginx   20 Oct 29 13:12 ..
drwxrwxr-x. 8 sawaliram sawaliram 4096 Mar  1 13:42 code
drwxrwxr-x. 5 sawaliram sawaliram   65 Oct 29 14:07 env
-rwxrw-r--. 1 sawaliram sawaliram  521 Mar  7 12:26 gunicorn_start
drwxrwxr-x. 2 sawaliram sawaliram   51 Mar  7 14:46 logs
drwxrwxrwx. 2 sawaliram nginx    6 Mar  7 12:29 run
```
I tried to find out if this is a issue with the django app, but with no errors being thrown by gunicorn when from inside the virtual environment, I can't say for sure what the problem is.

**Comment by nitinpaul** [comment]
Adding the journalctl output after restarting gunicorn:

```
$ sudo journalctl -u gunicorn

Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: application = get_wsgi_application()
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: django.setup(set_prefix=False)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __ge
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: self._setup(name)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _set
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: self._wrapped = Settings(settings_module)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/django/conf/__init__.py", line 126, in __i
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: Traceback (most recent call last):
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 210, in run
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: self.sleep()
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 360, in sleep
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: ready = select.select([self.PIPE[0]], [], [], 1.0)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: self.reap_workers()
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_wo
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: During handling of the above exception, another exception occurred:
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: Traceback (most recent call last):
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/bin/gunicorn", line 11, in <module>
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: sys.exit(run())
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: super(Application, self).run()
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: Arbiter(self).run()
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: self.stop()
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: time.sleep(0.1)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: self.reap_workers()
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: File "/home/sawaliram/sawaliram/website/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_wo
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Mar 11 12:59:16 sawaliram.tifrh.res.in gunicorn_start[25948]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Mar 11 12:59:16 sawaliram.tifrh.res.in systemd[1]: gunicorn.service: main process exited, code=exited, status=1/FAILURE
Mar 11 12:59:16 sawaliram.tifrh.res.in systemd[1]: Unit gunicorn.service entered failed state.
Mar 11 12:59:16 sawaliram.tifrh.res.in systemd[1]: gunicorn.service failed.
```

**Comment by nitinpaul** [comment]
It appears that the problem was that the unix ```service``` [strips all environment variables](https://unix.stackexchange.com/questions/44370/how-to-make-unix-service-see-environment-variables/44378#44378) except ```TERM```, ```PATH``` and ```LANG```, which was causing the Django app to not launch correctly. The solution was to create an environment file with the required variables and point to it in the ```gunicorn.service``` file like so:
```
[Service]
EnvironmentFile=/home/path/to/.env
```
